# https://github.com/google/mediapipe/blob/v0.7.5/mediapipe/framework/calculator.proto#L218

input_stream: "input_video"
output_stream: "output_video"

# https://github.com/google/mediapipe/blob/v0.7.5/mediapipe/framework/calculator.proto#L220
node {
  calculator: "TestCalculator"
  input_stream: "input_video"
  output_stream: "intermediate_video"
  node_options: {
    [type.googleapis.com/mediapipe.TestCalculatorOptions] {
      test_name: "test"

      test_values: "index:0"
      test_values: "index:1"
      test_values: "index:2"
    }
  }
}

# for Detection
node {
  calculator: "TestCalculator"
  input_stream: "intermediate_video"
  output_stream: "dropped_video"
  output_stream: "DETECTION:detection"
  output_stream: "DETECTIONS:detections"
}
output_stream: "detection"
output_stream: "detections"

# subgraph
node {
  calculator: "TestSubgraph"
  input_stream: "intermediate_video"
  output_stream: "output_video"
}

# side packet to stream.
node {
  calculator: "ConstantSidePacketCalculator"
  output_side_packet: "PACKET:0:constant_value_0"
  output_side_packet: "PACKET:1:constant_value_1"
  output_side_packet: "PACKET:2:constant_value_2"
  options: {
    [mediapipe.ConstantSidePacketCalculatorOptions.ext]: {
      packet { float_value: 1.1f }
      packet { float_value: 2.2f }
      packet { float_value: 3.3f }
    }
  }
}
node {
  calculator: "SidePacketToStreamCalculator"
  input_stream: "TICK:input_video"
  input_side_packet: "constant_value_0"
  input_side_packet: "constant_value_1"
  input_side_packet: "constant_value_2"
  input_side_packet: "user_value_0"
  output_stream: "AT_TICK:0:value_0"
  output_stream: "AT_TICK:1:value_1"
  output_stream: "AT_TICK:2:value_2"
  output_stream: "AT_TICK:3:value_3"
}
node {
  calculator: "ConcatenateFloatVectorCalculator"
  input_stream: "value_0"
  input_stream: "value_1"
  input_stream: "value_2"
  input_stream: "value_3"
  output_stream: "output_value"
}
output_stream: "output_value"
